### ISSUE TITLE
Localize ticket categories

### ISSUE THREAD

**Issue by madffm** [centosadmin/localizable#1]
Hi,

Is there any chance to add a feature to translate ticket categories aswell?
Or is this impossible by design?

Thanks
Matthias

**Comment by madffm** [comment]
Any news?

**Comment by reshetov** [comment]
The current implementation of the plugin will break the native names for the IssueCategory (it will be impossible to change the original category name on the edit category page). Therefore, I'm afraid that it's not possible to implement localization for the Issue Category model without huge changes to the base plugin methods.
